### ISSUE TITLE
Property 'observable' must be of type 'unique symbol', but here has type 'symbol'.

### ISSUE THREAD

**Issue by lajith111** [ghiscoding/Angular-Slickgrid#696]
Aftr upgranding to  "@types/node": "^14.14.27",

I am getting elow error

![image](https://user-images.githubusercontent.com/28708173/107871548-ad017300-6ec8-11eb-8ba3-e3c2dfb8fa9c.png)

Eror:
```
node_modules/angular-slickgrid/node_modules/rxjs/internal/symbol/observable.d.ts:4:18 - error TS2717: Subsequent property 
declarations must have the same type.  Property 'observable' must be of type 'unique symbol', but here has type 'symbol'.        

4         readonly observable: symbol;
                   ~~~~~~~~~~
```

**Comment by ghiscoding** [comment]
Your approach is wrong, there's nothing wrong with `@types/node`, the problem is that you're upgraded to a version of RxJS that I don't support. Angular-Slickgrid will only work with `v6.3.3` of RxJS, which you can see in the `package.json` [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/package.json#L110). You might ask why? Because there were major problem and differences with RxJS version `6.4.0` and up which would break anyone using a version below that and I don't want that, so I fixed it at that version, RxJS 7 is of course completely out of the picture without a major version of my lib and that won't happen until many months, I won't do a major version just to support RxJS 7... so all that to say, you'll have to stick with a lower version of RxJS.

Lastly the bot closed your issue because you completely erased the issue form. Please fill in the necessary info the next time around to avoid having your issue being closed, it's written on the first line of the form...
`<!-- YOU MUST FILL IN THIS ISSUE TEMPLATE OR ELSE IT WILL BE AUTO-CLOSE BY THE BOT -->`

**Comment by ghiscoding** [comment]
By looking at RxJS repo, I found this is bug caused in latest version 6.6.6 and also in version 7.beta9+ and it looks like the RxJS team will rollback their code change of that `symbol` Type causing issue. You can see more info in this Angular-CLI [issue](https://github.com/angular/angular-cli/issues/20248) and also in RxJS [issue](https://github.com/ReactiveX/rxjs/issues/5919)

Also note that I will support RxJS 7+ in the next major version of Angular-Slickgrid, which is probably couple months away (planning around summer or early summer), the next `major` version will be quite major, it will use my other lib [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) monorepo lib and the RxJS 7 part is now covered in this [PR](https://github.com/ghiscoding/slickgrid-universal/pull/280) which I just merged.
